# Generated by Django 4.0.5 on 2022-06-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField(verbose_name='geo')),
                ('wear', models.IntegerField(max_length=255, verbose_name='wear')),
                ('weather', models.FloatField(verbose_name='weather')),
                ('vegetation', models.FloatField(verbose_name='vegetation')),
                ('names', models.CharField(max_length=255, verbose_name='names')),
            ],
        ),
    ]
