# Generated by Django 4.0.5 on 2022-06-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='geometry',
            field=models.JSONField(verbose_name='geometry'),
        ),
    ]
