# Generated by Django 4.0.5 on 2022-06-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_alter_line_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='wear',
            field=models.FloatField(max_length=255, verbose_name='wear'),
        ),
    ]
