# Generated by Django 4.0.5 on 2022-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_alter_line_wear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='wear',
            field=models.FloatField(verbose_name='wear'),
        ),
    ]
